---
- name: Create guacamole-server directories
  file:
    path: "{{ guacamole_directories }}"
    state: directory

- name: Install Dependencies
  apt:
    name: "{{ guacamole_packages }}"
    state: present

- name: Download Server Binary
  get_url:
    url: "{{ guacamole_server_url }}"
    dest: /home/ansible/guacamole-server.tar.gz

- name: Download Client war file
  get_url:
    url: "{{guacamole_client_url}}"
    dest: "{{ guacamole_client_path }}"
  notify: restart tomcat

- name: Extract the guacamole-server
  unarchive:
    src: /home/ansible/guacamole-server.tar.gz
    dest: "{{ guacamole_server_path }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Run Configure 
  command:
    cmd: ./configure --with-init-dir=/etc/init.d
  args:
    chdir: "{{ guacamole_server_path }}"

- name: Run Make
  make:
    chdir: "{{ guacamole_server_path }}"

- name: Run Make Install
  make:
    chdir: "{{ guacamole_server_path }}"
    target: install
  notify: restart guacd

- name: Download the Ldap plugin
  get_url: 
    url: "{{ guacamole_ldap_url }}"
    dest: /home/ansible/guacamole-auth-ldap-1.0.0.tar.gz

- name: Extract the guacamole auth-ldap extension
  unarchive:
    src: /home/ansible/guacamole-auth-ldap-1.0.0.tar.gz
    dest: "{{ guacamole_extension_path }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Copy the configuration to nginx server
  copy:
    src: guacamole.properties
    dest: /etc/guacamole/guacamole.properties


- import_tasks: mysql.yml
- import_tasks: nginx.yml