---
- name: Install Nginx reverse proxy
  apt:
    name: "{{ gucamole_nginx_packages }}"
    state: latest

- name: Copy the configuration to nginx server
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/gucamole.conf
  notify: restart nginx

- name: create symlink
  file:
    src: /etc/nginx/sites-available/gucamole.conf
    dest: /etc/nginx/sites-enabled/gucamole.conf
    state: link
  notify: restart nginx